### ISSUE TITLE
Перевести CSS в SASS

### ISSUE THREAD

**Issue by egorsmkv** [radio-t/site-css#3]
Это только предложение.

Многие уже не используют чистый CSS для разработки, поэтому предлагаю перевести CSS-код в [SASS](sass-lang.com).

**Comment by SmartFinn** [comment]
@egorsmkv а как быть с теми кто использует LESS, Stylus или PostCSS? Да и нет большой проблемы сконвертировать CSS в SASS локально и запушить CSS обратно.

**Comment by egorsmkv** [comment]
@SmartFinn моя идея в том, чтобы уйти от CSS, а куда уйти это уже как большинство решит.

**Comment by SmartFinn** [comment]
@egorsmkv а нет золотой середины, точнее есть, CSS называется. Кроме этого перед деплоем еще и транспайлинг запускать придется. В общем не нужно усложнять то что и так работает.

**Comment by umputun** [comment]
по моему, это плохая идея.

1. лишний этап к процессу построения
2. зачем? мотивация "так сейчас носят" это не мотвиация. 
3. Какую именно проблему, из тех что у нас есть, этот переход должен решить?

**Comment by egorsmkv** [comment]
По-моему, этот этап для построения не так сложен сейчас, когда можно сложить всё в контейнер и запустить команду deploy.

Мотивация в том, чтобы перевести 2k+ строк кода на CSS в модульную структуру SASS или другого генератора стилей.

**Comment by umputun** [comment]
ну может и не такая плохая :) раньше в octopress было именно так с SASS. Однако мне, как единственному редактору этих стилей, оно скорее мешало, т.к. для меня всегда было загадкой как точно мое изменение будет выглядеть и где. Сейчас, на мой вкус стало более явно все, во всяком случае на моем уровне понимания этих стилей.

**Comment by igoradamenko** [comment]
Сасс тут не нужен. Он делу не поможет.

> Мотивация в том, чтобы перевести 2k+ строк кода на CSS в модульную структуру SASS или другого генератора стилей.

Ключевым тут должна быть модульная структура, а не Сасс :) Сейчас стили прям сильно запутаны, и изменение размера шрифта в одном месте может вызвать тот ещё эффект бабочки. 

Тут БЭМа не хватает, или чего-нибудь смежного.
