### ISSUE TITLE
Исправить все ошибки stylelint

### ISSUE THREAD

**Issue by SmartFinn** [radio-t/site-css#5]
Есть желание исправить все ошибки которые находит stylelint

![screenshot from 2016-12-23 19-31-36](https://cloud.githubusercontent.com/assets/819186/21459720/70ed92f0-c949-11e6-88d7-b9cbc1861de2.png)

Так как это не визуальное улучшение, я решил сперва спросить приветствуется ли такое изменение чтобы случайно не сделать много скучной работы в пустоту.

**Comment by SmartFinn** [comment]
Даже если опустить все warning с отступами и отсутствующими `;`, ошибок там не мало

![screenshot from 2016-12-23 19-46-07](https://cloud.githubusercontent.com/assets/819186/21460441/fb4af698-c950-11e6-9d24-2700bb7f8f4c.png)

кроме стилистических, при беглом просмотре, я нашел опечатки (`pagging` вместо `padding`), неправильно закомментированные строчки (`#`)  и подозреваю что это только вершина айсберга.

**Comment by umputun** [comment]
починка ошибок - это хорошее дело
